name: Deploy Shopix

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/shopix-frontend:${{ github.sha }}
          ${{ secrets.DOCKER_HUB_USERNAME }}/shopix-frontend:latest
        cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/shopix-frontend:latest
        cache-to: type=inline

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          mkdir ~/shopix-frontend
          cd ~/shopix-frontend
          cat > docker-compose.yml << EOF
          version: '3'
          services:
            shopix:
              image: ${{ secrets.DOCKER_HUB_USERNAME }}/shopix-frontend:latest
              restart: always
              ports:
                - "8080:80"
          EOF
          docker compose down
          docker compose pull
          docker compose up -d
