name: Deploy Shopix

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
        name: Deploy
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup SSH
              uses: webfactory/ssh-agent@v0.8.0
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            - name: Add known hosts
              run: |
                  mkdir -p ~/.ssh
                  ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
            - name: Deploy to Server
              run: |
                  ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "\
                  echo 'Starting deployment...' && \
                  mkdir -p ~/shopix-frontend && \
                  cd ~/shopix-frontend && \
                  if [ ! -d .git ]; then \
                    echo 'Initializing git repository...' && \
                    git init && \
                    git remote add origin git@github.com:MTUCI-Pixel-Team/shopix-frontend.git && \
                    git fetch && \
                    git checkout -f main; \
                  else \
                    git fetch && \
                    git reset --hard origin/main; \
                  fi && \
                  cat > docker-compose.yml << EOF
                  version: '3'
                  services:
                    shopix:
                      build:
                        context: .
                      restart: always
                      env_file:
                        - .env
                      ports:
                        - "8080:80"
                  EOF && \
                  docker compose pull && \
                  docker compose down --remove-orphans && \
                  docker compose up -d --build && \
                  echo 'Deployment completed successfully'"
              timeout-minutes: 10
