name: Build and deploy

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '20'

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v2
              with:
                  context: .
                  push: true
                  tags: ${{ secrets.DOCKER_HUB_USERNAME }}/shopix-frontend:${{ github.sha }}

            - name: Deploy to server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: ${{ secrets.SERVER_USER }}
                  password: ${{ secrets.SERVER_PASSWORD }}
                  script: |
                      docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/shopix-frontend:${{ github.sha }}
                      docker stop shopix-frontend || true
                      docker rm shopix-frontend || true
                      docker run -d --name shopix-frontend -p 5000:5000 ${{ secrets.DOCKER_HUB_USERNAME }}/shopix-frontend:${{ github.sha }}
