name: Build and Deploy

on:
    push:
        branches:
            - dev
    pull_request:
        branches:
            - dev

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '20'

            - name: Install Dependencies
              run: npm install

            - name: Build
              run: npm run build

            - name: Deploy to main
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                git config --global user.name 'GitHub Actions Bot'
                git config --global user.email '<>'
                git fetch
                git checkout main
                git merge dev --strategy-option=theirs
                git push origin main
